#!/usr/bin/env python3

###nbformat use to drop the first notebook cell, based on https://stackoverflow.com/a/71244733/8508004 to get second cell forward.
# Don't want first cell because first cell currently, which is ast https://nbviewer.org/github/dbikard/genomenotebook/blob/d6f8a1e9cf56277869a822e050a7cb9f7d09a5e5/nbs/00_Examples.ipynb , is above the main title and starts with `#| hide`
cell_to_start_collecting_at = 2 # number of cell to start the span of cells to collect; first cell gets number 1 in bracket if run so use that numbering
length_of_cell_block_to_keep = 2000 # length of sequential span of cells to keep
import nbformat as nbf
ntbk = nbf.read("nbs/00_Examples.ipynb", nbf.NO_CONVERT)
new_ntbk = ntbk
new_ntbk.cells = [cell for indx, cell in enumerate(ntbk.cells) if cell_to_start_collecting_at - 2 < indx < (cell_to_start_collecting_at + length_of_cell_block_to_keep - 1)]
nbf.write(new_ntbk, "nbs/00_Examples.ipynb", version=nbf.NO_CONVERT)
###END OF nbformat use to drop the first notebook cell.



